language: ruby
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- cp config/secrets.travis.yml config/secrets.yml
script:
- scss-lint --config=.scss-lint.yml app/assets/stylesheets/**/*.scss
- bundle exec rspec

